import type { Lang } from "@/app/dictionaries/header";

type RoutesDictionary = {
  home: string;
  title: string;
  description: string;
  groupPrefix: string;
  insurancePrefix: string;
  backHome: string;
  empty: string;
  relatedTitle: string;
  viewAll: string;
  countries: Record<string, string>;
};

const countryNames: Record<string, Record<Lang, string>> = {
  belarus: { ru: "Беларусь", en: "Belarus", pl: "Białoruś", be: "Беларусь", uk: "Білорусь", kk: "Беларусь", uz: "Belarus", az: "Belarus", tr: "Belarus", ka: "ბელარუსი", hy: "Բելառուս", fa: "بلاروس", ckb: "بیلاڕوس", kmr: "Belarûs", ar: "بيلاروس", he: "בלארוס", ro: "Belarus", sr: "Белорусија", sq: "Bjellorusia", mn: "Беларусь" },
  poland: { ru: "Польша", en: "Poland", pl: "Polska", be: "Польшча", uk: "Польща", kk: "Польша", uz: "Polsha", az: "Polşa", tr: "Polonya", ka: "პოლონეთი", hy: "Լեհաստան", fa: "لهستان", ckb: "پۆڵەندا", kmr: "Polonya", ar: "بولندا", he: "פולין", ro: "Polonia", sr: "Пољска", sq: "Polonia", mn: "Польш" },
  lithuania: { ru: "Литва", en: "Lithuania", pl: "Litwa", be: "Літва", uk: "Литва", kk: "Литва", uz: "Litva", az: "Litva", tr: "Litvanya", ka: "ლიტვა", hy: "Լիտվա", fa: "لیتوانی", ckb: "لیتوانیا", kmr: "Lîtvanya", ar: "ليتوانيا", he: "ליטא", ro: "Lituania", sr: "Литванија", sq: "Lituania", mn: "Литва" },
  georgia: { ru: "Грузия", en: "Georgia", pl: "Gruzja", be: "Грузія", uk: "Грузія", kk: "Грузия", uz: "Gruziya", az: "Gürcüstan", tr: "Gürcistan", ka: "საქართველო", hy: "Վրաստան", fa: "گرجستان", ckb: "گورجستان", kmr: "Gurcistan", ar: "جورجيا", he: "גאורגיה", ro: "Georgia", sr: "Грузија", sq: "Gjeorgjia", mn: "Гүрж" },
  romania: { ru: "Румыния", en: "Romania", pl: "Rumunia", be: "Румынія", uk: "Румунія", kk: "Румыния", uz: "Ruminiya", az: "Rumıniya", tr: "Romanya", ka: "რუმინეთი", hy: "Ռումինիա", fa: "رومانی", ckb: "ڕۆمانیا", kmr: "Romanya", ar: "رومانيا", he: "רומניה", ro: "România", sr: "Румунија", sq: "Rumania", mn: "Румын" },
  bulgaria: { ru: "Болгария", en: "Bulgaria", pl: "Bułgaria", be: "Балгарыя", uk: "Болгарія", kk: "Болгария", uz: "Bolgariya", az: "Bolqarıstan", tr: "Bulgaristan", ka: "ბულგარეთი", hy: "Բուլղարիա", fa: "بلغارستان", ckb: "بولگاریا", kmr: "Bulgaristan", ar: "بلغاريا", he: "בולגריה", ro: "Bulgaria", sr: "Бугарска", sq: "Bullgaria", mn: "Болгар" },
  greece: { ru: "Греция", en: "Greece", pl: "Grecja", be: "Грэцыя", uk: "Греція", kk: "Грекия", uz: "Gretsiya", az: "Yunanıstan", tr: "Yunanistan", ka: "საბერძნეთი", hy: "Հունաստան", fa: "یونان", ckb: "یۆنان", kmr: "Yewnanistan", ar: "اليونان", he: "יוון", ro: "Grecia", sr: "Грчка", sq: "Greqia", mn: "Грек" },
  kazakhstan: { ru: "Казахстан", en: "Kazakhstan", pl: "Kazachstan", be: "Казахстан", uk: "Казахстан", kk: "Қазақстан", uz: "Qozog‘iston", az: "Qazaxıstan", tr: "Kazakistan", ka: "ყაზახეთი", hy: "Ղազախստան", fa: "قزاقستان", ckb: "کازاخستان", kmr: "Qazaxistan", ar: "كازاخستان", he: "קזחסטן", ro: "Kazahstan", sr: "Казахстан", sq: "Kazakistani", mn: "Казахстан" },
  uae: { ru: "ОАЭ", en: "UAE", pl: "ZEA", be: "ААЭ", uk: "ОАЕ", kk: "БАӘ", uz: "BAA", az: "BƏƏ", tr: "BAE", ka: "არაბთა გაერთიანებული საამიროები", hy: "ԱՄԷ", fa: "امارات", ckb: "ئیمارات", kmr: "Îmarat", ar: "الإمارات", he: "איחוד האמירויות", ro: "EAU", sr: "УАЕ", sq: "EBA", mn: "АНЭУ" },
  albania: { ru: "Албания", en: "Albania", pl: "Albania", be: "Албанія", uk: "Албанія", kk: "Албания", uz: "Albaniya", az: "Albaniya", tr: "Arnavutluk", ka: "ალბანეთი", hy: "Ալբանիա", fa: "آلبانی", ckb: "ئەلبانیا", kmr: "Albanya", ar: "ألبانيا", he: "אלבניה", ro: "Albania", sr: "Албанија", sq: "Shqipëria", mn: "Албани" },
  algeria: { ru: "Алжир", en: "Algeria", pl: "Algieria", be: "Алжыр", uk: "Алжир", kk: "Алжир", uz: "Jazoir", az: "Əlcəzair", tr: "Cezayir", ka: "ალჟირი", hy: "Ալժիր", fa: "الجزایر", ckb: "جەزائیر", kmr: "Cezayîr", ar: "الجزائر", he: "אלג'יריה", ro: "Algeria", sr: "Алжир", sq: "Algjeria", mn: "Алжир" },
  france: { ru: "Франция", en: "France", pl: "Francja", be: "Францыя", uk: "Франція", kk: "Франция", uz: "Fransiya", az: "Fransa", tr: "Fransa", ka: "საფრანგეთი", hy: "Ֆրանսիա", fa: "فرانسه", ckb: "فەڕەنسا", kmr: "Fransa", ar: "فرنسا", he: "צרפת", ro: "Franța", sr: "Француска", sq: "Franca", mn: "Франц" },
};

const base: Record<Lang, Omit<RoutesDictionary, "countries">> = {
  ru: { home: "Главная", title: "Все маршруты страхования", description: "Выберите страну регистрации автомобиля и направление поездки, чтобы открыть подходящую страницу о страховании и документах для маршрута.", groupPrefix: "Автомобили из", insurancePrefix: "Страховка", backHome: "Вернуться на главную", empty: "Для этого языка маршрутные страницы пока не опубликованы.", relatedTitle: "Другие маршруты страхования", viewAll: "Посмотреть все маршруты" },
  en: { home: "Home", title: "All insurance routes", description: "Choose the vehicle registration country and travel destination to find the relevant route insurance and document guide.", groupPrefix: "Vehicles from", insurancePrefix: "Insurance", backHome: "Back to home", empty: "No route pages are published in this language yet.", relatedTitle: "Other insurance routes", viewAll: "View all routes" },
  pl: { home: "Strona główna", title: "Wszystkie trasy ubezpieczeniowe", description: "Wybierz kraj rejestracji pojazdu i cel podróży, aby znaleźć odpowiednią stronę o ubezpieczeniu i dokumentach.", groupPrefix: "Pojazdy z kraju", insurancePrefix: "Ubezpieczenie", backHome: "Wróć na stronę główną", empty: "W tym języku nie opublikowano jeszcze stron tras.", relatedTitle: "Inne trasy ubezpieczeniowe", viewAll: "Zobacz wszystkie trasy" },
  be: { home: "Галоўная", title: "Усе страхавыя маршруты", description: "Выберыце краіну рэгістрацыі аўтамабіля і напрамак паездкі, каб адкрыць адпаведную старонку пра страхаванне і дакументы.", groupPrefix: "Аўтамабілі з", insurancePrefix: "Страхаванне", backHome: "Вярнуцца на галоўную", empty: "Для гэтай мовы старонкі маршрутаў пакуль не апублікаваныя.", relatedTitle: "Іншыя страхавыя маршруты", viewAll: "Паглядзець усе маршруты" },
  kk: { home: "Басты бет", title: "Барлық сақтандыру бағыттары", description: "Сақтандыру және құжаттар туралы тиісті бетті табу үшін көліктің тіркелген елін және сапар бағытын таңдаңыз.", groupPrefix: "Көліктер шыққан ел", insurancePrefix: "Сақтандыру", backHome: "Басты бетке оралу", empty: "Бұл тілде бағыт беттері әлі жарияланбаған.", relatedTitle: "Басқа сақтандыру бағыттары", viewAll: "Барлық бағыттарды көру" },
  ka: { home: "მთავარი", title: "დაზღვევის ყველა მარშრუტი", description: "აირჩიეთ ავტომობილის რეგისტრაციის ქვეყანა და მგზავრობის მიმართულება დაზღვევისა და დოკუმენტების შესაბამისი გვერდის სანახავად.", groupPrefix: "ავტომობილები ქვეყნიდან", insurancePrefix: "დაზღვევა", backHome: "მთავარ გვერდზე დაბრუნება", empty: "ამ ენაზე მარშრუტის გვერდები ჯერ არ გამოქვეყნებულა.", relatedTitle: "დაზღვევის სხვა მარშრუტები", viewAll: "ყველა მარშრუტის ნახვა" },
  hy: { home: "Գլխավոր", title: "Ապահովագրության բոլոր երթուղիները", description: "Ընտրեք մեքենայի գրանցման երկիրը և ուղևորության ուղղությունը՝ ապահովագրության համապատասխան էջը գտնելու համար։", groupPrefix: "Մեքենաներ երկրից", insurancePrefix: "Ապահովագրություն", backHome: "Վերադառնալ գլխավոր էջ", empty: "Այս լեզվով երթուղիների էջեր դեռ չկան։", relatedTitle: "Ապահովագրության այլ երթուղիներ", viewAll: "Դիտել բոլոր երթուղիները" },
  ar: { home: "الرئيسية", title: "جميع مسارات التأمين", description: "اختر بلد تسجيل المركبة ووجهة السفر للوصول إلى صفحة التأمين والمستندات المناسبة للمسار.", groupPrefix: "مركبات من", insurancePrefix: "تأمين", backHome: "العودة إلى الرئيسية", empty: "لم تُنشر صفحات مسارات بهذه اللغة بعد.", relatedTitle: "مسارات تأمين أخرى", viewAll: "عرض جميع المسارات" },
  sq: { home: "Kryefaqja", title: "Të gjitha itineraret e sigurimit", description: "Zgjidhni vendin e regjistrimit të automjetit dhe destinacionin për të gjetur udhëzuesin përkatës të sigurimit.", groupPrefix: "Automjete nga", insurancePrefix: "Sigurimi", backHome: "Kthehu në kryefaqe", empty: "Nuk ka ende faqe itinerari në këtë gjuhë.", relatedTitle: "Itinerare të tjera sigurimi", viewAll: "Shiko të gjitha itineraret" },
  uk: { home: "Головна", title: "Усі страхові маршрути", description: "Оберіть країну реєстрації автомобіля та напрямок поїздки, щоб знайти відповідну сторінку про страхування.", groupPrefix: "Автомобілі з", insurancePrefix: "Страхування", backHome: "Повернутися на головну", empty: "Цією мовою сторінки маршрутів ще не опубліковані.", relatedTitle: "Інші страхові маршрути", viewAll: "Переглянути всі маршрути" },
  uz: { home: "Bosh sahifa", title: "Barcha sug‘urta yo‘nalishlari", description: "Tegishli sug‘urta sahifasini topish uchun avtomobil ro‘yxatdan o‘tgan mamlakat va safar yo‘nalishini tanlang.", groupPrefix: "Avtomobillar mamlakati", insurancePrefix: "Sug‘urta", backHome: "Bosh sahifaga qaytish", empty: "Bu tilda yo‘nalish sahifalari hali e’lon qilinmagan.", relatedTitle: "Boshqa sug‘urta yo‘nalishlari", viewAll: "Barcha yo‘nalishlarni ko‘rish" },
  az: { home: "Ana səhifə", title: "Bütün sığorta marşrutları", description: "Uyğun sığorta səhifəsini tapmaq üçün avtomobilin qeydiyyat ölkəsini və səfər istiqamətini seçin.", groupPrefix: "Avtomobillər bu ölkədən", insurancePrefix: "Sığorta", backHome: "Ana səhifəyə qayıt", empty: "Bu dildə marşrut səhifələri hələ dərc edilməyib.", relatedTitle: "Digər sığorta marşrutları", viewAll: "Bütün marşrutlara bax" },
  tr: { home: "Ana Sayfa", title: "Tüm sigorta rotaları", description: "İlgili sigorta sayfasını bulmak için aracın kayıt ülkesini ve seyahat hedefini seçin.", groupPrefix: "Araçların çıkış ülkesi", insurancePrefix: "Sigorta", backHome: "Ana sayfaya dön", empty: "Bu dilde henüz rota sayfası yayımlanmadı.", relatedTitle: "Diğer sigorta rotaları", viewAll: "Tüm rotaları görüntüle" },
  fa: { home: "صفحه اصلی", title: "همه مسیرهای بیمه", description: "برای یافتن صفحه مناسب بیمه، کشور ثبت خودرو و مقصد سفر را انتخاب کنید.", groupPrefix: "خودروها از", insurancePrefix: "بیمه", backHome: "بازگشت به صفحه اصلی", empty: "هنوز صفحه مسیری به این زبان منتشر نشده است.", relatedTitle: "سایر مسیرهای بیمه", viewAll: "مشاهده همه مسیرها" },
  he: { home: "דף הבית", title: "כל מסלולי הביטוח", description: "בחרו את מדינת רישום הרכב ואת יעד הנסיעה כדי למצוא את עמוד הביטוח המתאים.", groupPrefix: "כלי רכב מ", insurancePrefix: "ביטוח", backHome: "חזרה לדף הבית", empty: "טרם פורסמו עמודי מסלול בשפה זו.", relatedTitle: "מסלולי ביטוח נוספים", viewAll: "הצגת כל המסלולים" },
  ro: { home: "Acasă", title: "Toate rutele de asigurare", description: "Alegeți țara de înmatriculare și destinația pentru a găsi pagina de asigurare potrivită.", groupPrefix: "Vehicule din", insurancePrefix: "Asigurare", backHome: "Înapoi acasă", empty: "Nu există încă pagini de rută în această limbă.", relatedTitle: "Alte rute de asigurare", viewAll: "Vezi toate rutele" },
  sr: { home: "Почетна", title: "Све руте осигурања", description: "Изаберите земљу регистрације возила и одредиште да бисте пронашли одговарајућу страницу осигурања.", groupPrefix: "Возила из", insurancePrefix: "Осигурање", backHome: "Назад на почетну", empty: "Још нема страница рута на овом језику.", relatedTitle: "Друге руте осигурања", viewAll: "Прикажи све руте" },
  ckb: { home: "سەرەکی", title: "هەموو ڕێگاکانی بیمە", description: "وڵاتی تۆمارکردنی ئۆتۆمبێل و شوێنی گەشت هەڵبژێرە بۆ دۆزینەوەی لاپەڕەی بیمەی گونجاو.", groupPrefix: "ئۆتۆمبێل لە", insurancePrefix: "بیمە", backHome: "گەڕانەوە بۆ سەرەکی", empty: "هێشتا لاپەڕەی ڕێگا بەم زمانە بڵاونەکراوەتەوە.", relatedTitle: "ڕێگاکانی تری بیمە", viewAll: "هەموو ڕێگاکان ببینە" },
  kmr: { home: "Rûpela Sereke", title: "Hemî rêyên sîgorteyê", description: "Welatê tomarkirina wesayîtê û armanca rêwîtiyê hilbijêrin da ku rûpela sîgorteyê bibînin.", groupPrefix: "Wesayît ji", insurancePrefix: "Sîgorte", backHome: "Vegere rûpela sereke", empty: "Hêj rûpelên rêyê bi vî zimanî nehatine weşandin.", relatedTitle: "Rêyên din ên sîgorteyê", viewAll: "Hemî rêyan bibîne" },
  mn: { home: "Нүүр хуудас", title: "Бүх даатгалын чиглэл", description: "Тохирох даатгалын хуудсыг олохын тулд автомашины бүртгэлийн улс болон аяллын чиглэлийг сонгоно уу.", groupPrefix: "Автомашины улс", insurancePrefix: "Даатгал", backHome: "Нүүр хуудас руу буцах", empty: "Энэ хэлээр чиглэлийн хуудас хараахан нийтлэгдээгүй байна.", relatedTitle: "Бусад даатгалын чиглэл", viewAll: "Бүх чиглэлийг үзэх" },
};

export function getRoutesDictionary(lang: Lang): RoutesDictionary {
  return {
    ...base[lang],
    countries: Object.fromEntries(
      Object.entries(countryNames).map(([slug, names]) => [slug, names[lang]]),
    ),
  };
}
